select bookname, price from book;
select * from book;
select distinct publisher from book;
select * from book where price < 20000;
select * from book where price between 1000 and 20000;
select * from book where price >= 10000 AND price <= 20000;
select * from book where publisher in ('굿스포츠', '대한미디어');
select * from book where publisher not in ('굿스포츠', '대한미디어');
select bookname, publisher from book where bookname LIKE '축구의 역사';
select bookname, publisher from book where bookname LIKE '%축구%';
select * from book where bookname LIKE '_구%';
select * from book where bookname LIKE '%축구%' AND price >= 20000;
select * from book where publisher='굿스포츠' or publisher='대한미디어';
select * from book where publisher in ('굿스포츠', '대한미디어');
select * from book order by bookname;
select * from book order by price, bookname;
select * from book order by price desc, publisher asc;
select sum(saleprice) from orders;
select sum(saleprice) AS 총매출 from orders;
select sum(saleprice) AS 총매출 from orders where custid=2;
select sum(saleprice) AS Total, avg(saleprice) as average, min(saleprice) as minimum, max(saleprice) as maximum from orders;
select count(*) from orders;
select custid, count(*) as 도서수량, sum(saleprice) as 총액 from orders group by custid;
select custid, count(*) as 도서수량 from orders where saleprice >= 8000 group by custid having count(*) >= 2;
select * from customer, orders;
select * from customer, orders where customer.custid = orders.custid;
select * from customer, orders where customer.custid = orders.custid order by customer.custid;
select name, saleprice from customer, orders where customer.custid = orders.custid;
select name, sum(saleprice) from customer, orders where customer.custid = orders.custid group by customer.name order by customer.name;
select customer.name, book.bookname from customer, orders, book where customer.custid = orders.custid and orders.bookid = book.bookid;
select customer.name, book.bookname from customer, orders, book where customer.custid = orders.custid and orders.bookid = book.bookid and book.price = 20000;
select customer.name, saleprice from customer left outer join orders on customer.custid = orders.custid;
select bookname from book where price = (select max(price) from book);
select name from customer where custid in (select custid from orders);
select name from customer where custid in (select custid from orders where bookid in (select bookid from book where publisher='대한미디어'));
select b1.bookname from book b1 where price > (select avg(b2.price) from book b2 where b2.publisher=b1.publisher);
select name from customer where address like '%대한민국%' union select name from customer where custid in (select custid from orders);
select name, address from customer cs where exists (select * from orders od where cs.custid = od.custid);